### ISSUE TITLE
Clicking across homepage timeline causes the map to disappear and reappear

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#114]
When clicking on timeline bubbles in Safari, the map disappears for ~2sec and then reappears. The disappearance is shorter on Chrome, but still visible.

**Comment by gregallensworth** [comment]
The charting system is redrawing based on new data. Part of the redraw is that it destroys and creates the map-chart. I'll see about "just" updating the data series without destroying the chart, That should greatly improve the performance.

**Comment by gregallensworth** [comment]
Refactored a bit, so that after the map/chart already exists, a simple `setData()` will be called rather tyhan destroying and re-creating the map. This should give a significant performance boost.

*Note for testing* that your debugger may be set to disable cache. In real-world conditions, after the CSV is initially loaded it would be present in cache, so switching years (not not district-types) would be nearly instant.

**Comment by migurski** [comment]
Looks good!
