### ISSUE TITLE
Custom Analytics events

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#127]
Pulling out of #125:

Currently have no custom events on state pages.

Minimally we should:
* Track all hash changes to capture house level, plans, and elections

Bonus:
* Which metric tab is live

**Comment by gregallensworth** [comment]
When one changes year, election-or-plan, or district type a GA event is sent.

```
ea: statedetails
ec: election
el: ushouse
ev: 1988
```

**Comment by gregallensworth** [comment]
An event is logged when one changes metric tabs. No specification was given, so I went with this:

```
dl: http://local.planscore.info/california/         page URL + state
ea: metricdetails               event type
ec: meanmedian                  event category, the metric
el: ushouse-plan                event label, level+plan/election
ev: 1986                        event value, year
```

Note that this occurs when one *changes* the metric being shown, so there will not be a glut of EG logs due to page loads. Tough choice here: over-report selection of EG metric due to page loading, or under-report the selection of EG metric by virtue of it already being visible so one didn't need to select it?

**Comment by danrademacher** [comment]
Let's have @migurski confirm these are coming through on his GA dashboard, and also weigh in on the EG over or undercount.

**Comment by migurski** [comment]
I see things in GA, so it seems to be working well!

<img width="668" alt="screen shot 2018-01-06 at 9 16 54 am" src="https://user-images.githubusercontent.com/58730/34642082-64d41e8c-f2c2-11e7-8312-e93466b331dc.png">

Greg, your suggested trade-off seems fine.
