### ISSUE TITLE
Additional content thought for metric pages

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#145]
Idea: the individual metric pages like https://planscore.org/efficiencygap/ feel like they could use a good set of examples. Here are some extreme outliers for each metric that could be illustrated there with an appropriate chart:

- EG (D) 20% https://planscore.org/texas/#!1994-plan-ushouse
- EG (R) 20% https://planscore.org/north_carolina/#!2012-plan-ushouse
- PB (D) 25% https://planscore.org/maryland/#!2012-plan-ushouse
- PB (R) 27% https://planscore.org/alabama/#!2016-plan-ushouse
- MM (R) 11% https://planscore.org/georgia/#!2006-plan-ushouse
- MM (D) 10% https://planscore.org/kentucky/#!1980-plan-ushouse

I’m expecting sample graph styles from Nick or Ruth for MM and PB. Does seem potentially useful to link to a metric directly; all the URLs above show EG tab open. Curious to hear thoughts on this.

**Comment by gregallensworth** [comment]
I have some ideas as to how we could link too a state page with not only the year/level/plan-election selected, but also the metric tab. URL formats would be as follows:

https://planscore.org/texas/#!1994-plan-ushouse-eg
https://planscore.org/north_carolina/#!2012-plan-ushouse-eg
https://planscore.org/maryland/#!2012-plan-ushouse-pb
https://planscore.org/alabama/#!2016-plan-ushouse-pb
https://planscore.org/georgia/#!2006-plan-ushouse-mm
https://planscore.org/kentucky/#!1980-plan-ushouse-mm

There should be no need to modify existing hyperlinks to use the new URLs, as I would modify `initLoadInitialConditions()` to make these "components" more modular: year if specified, plan/election if specified, district type if specified, ... and metric tab if specified.

Work to be done on state details page:
- [ ] rework `initLoadInitialConditions()` to apply params separately instead of as a regex string
- [ ] `initLoadInitialConditions()` to select `-metric` component
- [ ] `updateHashUrl()` changes to adjust metric tab component as well, when tab is changed

**Comment by migurski** [comment]
That looks like a good solution, Greg!
