### ISSUE TITLE
Shrink vertical whitespace on home page for phones

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#166]
There's a lot of extra space above and below the map on certain phone screens.

iPhone 5:

<img width="320" alt="screen shot 2018-01-15 at 10 37 23 am" src="https://user-images.githubusercontent.com/58730/34956965-58950ada-f9e0-11e7-90e3-f981a228f838.png">

iPhone 6:

<img width="332" alt="screen shot 2018-01-15 at 10 37 37 am" src="https://user-images.githubusercontent.com/58730/34956961-54a70df6-f9e0-11e7-827d-bb5cd1e40134.png">

**Comment by gregallensworth** [comment]
I have added some more mobile-size behaviors to help mitigate this. There will be limits, as the rectangular area is the Highcharts chart and we don't have 100% pixel control over the spacings there. But, this does help a lot as a first pass.

![image](https://user-images.githubusercontent.com/3117633/35001843-a63c9b7e-fa9c-11e7-9861-b639271900a6.png)

* On `xs` screens there is now a `max-height: 66vw;` on the #map so as to constraint its height to 2/3 the window width. Experimentally this seems to give very good results.
* At 320px width, the Most Biased Plans legend touches TX and FL to a degree that can obscure FL. I added two factors to improve this: a reduction in font-size and also changing its wording to "Most biased plans" so the extra words "in our data" do not obscure FL..

**Comment by danrademacher** [comment]
Spacing above the map looks good to me. The legend/map collision below seems problematic. Not sure I fully understand the limits on what we can do here. Is it possible to give the legend its own space below the map but just with less blank space?

**Comment by gregallensworth** [comment]
Sure, moving the legend out from the map puts it clear from obscuring FL and TX on even the smallest screens. But the designs originally called for it to be in the map's area, so as to achieve a tighter spacing.

Reworked to be outside the map area, desktop size:

![image](https://user-images.githubusercontent.com/3117633/35004709-f55dbaea-faa5-11e7-820b-666311b06ad8.png)

Reworked to be outside the map, mobile:

![image](https://user-images.githubusercontent.com/3117633/35004747-08934bb6-faa6-11e7-8590-11b23c257108.png)


I can continue working on it for as while, see about on desktop-only positioning it into the corner of the map so as to achieve the tighter spacing.

**Comment by gregallensworth** [comment]
Here we go. Up until big-desktop size, the legend stays in its own section below the map. At big-desktop size, it gets some positioning hacks to try and place it inside the map area so as not to waste vertical space.

Phone, Tablet, Desktop:

![phone](https://user-images.githubusercontent.com/3117633/35005602-ca528af8-faa8-11e7-8d9d-5919ce333b1b.png)
![tablet](https://user-images.githubusercontent.com/3117633/35005604-ca73aeae-faa8-11e7-87fc-de006cbd4171.png)
![wide](https://user-images.githubusercontent.com/3117633/35005605-caa9d740-faa8-11e7-8f85-5cd88246dd45.png)


Up until 768 I think it looks better down in its separate area. At 1001 it changes to large-desktop and the position of the legend can be known due to the sizewide max-width. In the 768-1000 range there's a lot of variation as to the best pixel size to position the legend into the Gulf of Mexico. Then again, at these sizes I'm not sure it looks so great, looking more "imbalanced" than it does "tight" at the larger sizes.

Intermediate but forcing legend into GOM:

![image](https://user-images.githubusercontent.com/3117633/35005772-7051ae0c-faa9-11e7-94e3-496b4ae517c1.png)

**Comment by gregallensworth** [comment]
All righty, this is now in place on the live site. The legend remains in the Gulf of Mexico on all displays >= 768px width (tablet) and falls into its own area below the map on smaller (phone, small tablet).
