### ISSUE TITLE
Alabama state picker issue

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#167]
Plan dots not showing well:

![image](https://user-images.githubusercontent.com/1423200/35003492-dfdaa178-faa1-11e7-96c3-6162a5d62ef0.png)

https://planscore.org/alabama/#!2010-plan-statehouse-eg

**Comment by gregallensworth** [comment]
I see it. A combination of factors:

At one point it was decided to hide years for which we have no data. As such, about half of the years are omitted. Thus, half of the rows are hidden intentionally. That part is intentional, but potentially confusing when missing data are as severe as depicted here?

But the bigger item: The yearpicker looks for "the next year" e,g, comparing 2002 to 2000 to determine whether it is a new plan, comparing 2000 to 1998 to determine whether it is a new plan, comparing 1998 to 1996 to determine whether it is a new plan, and so on. In this case, 2000 and 1996 have no rows so this logic is failing: 2010, 2006, and 2002 are "new plans" since their previous-year is null and thus not the same plan.

* See about the ability of this logic to handle a row that is missing completely.

* Then review Alabama in light of this severity of missing-years data, and see whether the omission of nodata years is still a good idea.

**Comment by danrademacher** [comment]
Interesting. Both CSV data sources have a `plan` field which changes only when there's a new plan. So for AL in state data, we have:

year | code | plan
-- | -- | --
1974 | AL1974 | AL1
1978 | AL1978 | AL1
1982 | AL1982 | AL1.1
1986 | AL1986 | AL2
1990 | AL1990 | AL2
1994 | AL1994 | AL3
1998 | AL1998 | AL3
2002 | AL2002 | AL4
2006 | AL2006 | AL4
2010 | AL2010 | AL4
1992 | AK1992 | AK3

Instead of hiding years with no data and using assumed year increments to determine if there's a new plan, we should instead use the source data `year` to list unique available years directly, and then the `plan` to determine if plan changed.

**Comment by gregallensworth** [comment]
All fixed.

* Nodata years do remain hidden.
* Logic is reworked to properly tag continuing/starting plans even when there are gaps.

![image](https://user-images.githubusercontent.com/3117633/35015007-87b0d8f2-fac7-11e7-9f82-0a780deb5909.png)
