### ISSUE TITLE
Elections in odd years / 4-year cycles / Election schedule varies between states & district types

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#217]
One assumption of the Plan Picker for historical data is that elections are on even years. This is 100% true for US Congress in our data.

We just noticed that three states, covering 9 plans, have data falling on odd years:
```
KY1
MS1
MS2
MS3
MS4
VA2
VA3
VA4
VA5
```

None of that data is coming through. We noticed this in addressing #212 because the extreme case for State House is 17% Democratic bias for MS in 1979. so that sets the upper and lower bound of our EG histogram for State House. But we don't currently show that on the map because the picker assumes even-year data.

Not sure yet what solution is...

**Comment by danrademacher** [comment]
More detail on years_plans:

plancode | electionyear
-- | --
MS4 | 2003,2007,2011
MS3 | 1995,1999
MS2 | 1983,1987,1991
MS1 | 1979
VA5 | 2011,2013
VA4 | 2001,2003,2005,2007,2009
VA3 | 1991,1993,1995,1997,1999
VA2 | 1983,1985,1987,1989
KY1 | 1973,1975,1977,1979,1981

**Comment by danrademacher** [comment]
Not as easy as one might think, since the home page picker is fundamentally based on the idea of even-year elections.

But more problematic right now is how the VA page responds, for example, when I switch from US House to State House:
https://planscore.org/virginia/#!1982-plan-statehouse-eg

![image](https://user-images.githubusercontent.com/1423200/36180982-759140be-10d7-11e8-9993-7745017e5128.png)

**Comment by danrademacher** [comment]
Just to recap:

0/136 US House plans
9/208 State House plans
4/81 state senate plans.

about 3% of data. But some rather important data

**Comment by danrademacher** [comment]
Here are the offending states, house levels, and years:


state | houselevel | year
-- | -- | --
KY | state_house | 2014;2002;2004;2006;2008;2010;2012;1973;1975;1977;1979;1981;1996;1998;2000;1984;1986;1988;1990;1992;1994
MS | state_house | 2003;2007;2011;1995;1999;1983;1987;1991;1979
VA | state_house | 2011;2013;2001;2003;2005;2007;2009;1991;1993;1995;1997;1999;1983;1985;1987;1989
NJ | state_senate | 2003;2011
VA | state_senate | 2003;2011

**Comment by gregallensworth** [comment]
Possible solutions

### Front Page Map

The CSV loader could have a bunch of exceptions programmed into it to rewrite the CSV data ***for state house only*  when it is loaded. Imagine "if row.year=1979 and row.state=VA then row.year = 1980" as we rewrite the CSV in memory.

For this purely visual output, this should work A-OK. The 1992 year would silently show MS-1991 and VA-1991, for example, and 2012 would show NJ-2011 and VA-2011. Some savvy folks may raise an eyebrow that the map says 2012 and it's showing the 2011 plan, but that shouldn't be objectionable.

### State Page Year Picker

The year picker is first constructed in `initYearPickers()` which loops over the `PLAN_YEARS` constant, plain and simple. In theory, the list of years in `PLAN_YEARS` could be only a default and some states could get alternative lists of years to suit their needs.

```
let years = PLAN_YEARS;
if (state == 'KY') years = [ 1979, 1981, 1983, 1983, 1987, ... ];
else if (state == 'VA) years = [ 1977, 1979, 1981, 1983, 1985, 1987 ]; ...
```

Off the cuff, I think this would allow for even and also odd years, for the plan-span and plan-start highlighting to work as at present. The yearpicker is tagged with plan IDs and it is these plan IDs that are used for display of the plan statistics and loading of district polygons, so that should just work as well...

There's likely a piece or two I've not brained out yet, but these seem to cover the bulk of possibilities.

**Comment by gregallensworth** [comment]
#### State Page Year Picker

This round of commits adjusts the state page year picker, to use the actual years represented in the CSN data for the given state & districttype. This allows states to have any arbitrary years.

<img width="737" alt="2018-02-14 11_06_32-planscore __ virginia" src="https://user-images.githubusercontent.com/3117633/36222788-458831ac-1177-11e8-8d02-88c465852ff5.png">
<img width="737" alt="2018-02-14 11_06_44-planscore __ virginia" src="https://user-images.githubusercontent.com/3117633/36222789-45a55fd4-1177-11e8-990e-d9b5e7ccd2b2.png">
<img width="739" alt="2018-02-14 11_06_54-planscore __ kentucky" src="https://user-images.githubusercontent.com/3117633/36222790-45bffc2c-1177-11e8-9909-208a16bf9c63.png">
<img width="754" alt="2018-02-14 11_07_09-planscore __ kentucky" src="https://user-images.githubusercontent.com/3117633/36222791-45dc881a-1177-11e8-9a44-7b9e2f366ee4.png">
<img width="777" alt="2018-02-14 11_07_23-planscore __ kentucky" src="https://user-images.githubusercontent.com/3117633/36222792-45f3eff0-1177-11e8-892e-ec653a340706.png">
<img width="733" alt="2018-02-14 11_11_32-planscore __ alabama" src="https://user-images.githubusercontent.com/3117633/36222991-d9a588a8-1177-11e8-9a8f-bbaa06b79a73.png">


Items of note:
* Not every state & districttype has the same year range. KY ushouse, ranges 1972 - 1990
  * This results in inconsistent timelines between states, though also means fewer No Data conditions. In the case of KY the tradeoff is a smaller timeline, for not clicking the 13 most recent years which consistently have no data. A net gain in UX?
* See also Alabama statehouse (pictured above) which was a motivation for #167 in which we decided to always show all years instead of data-driven. Under this new behavior, their unusual 4-year cycle is still a new UX gain, in that the 50% of the timeline which had no data (1976, 1980, 1984, ...) is no longer present, inviting No Data conditions.
* Actual years may not be consecutive years, and may have variation. See the "1973-1981 Redistricting Plan" screenshot for an example, where we jump from 1981 to 1984 in the "same visual space" as any of the two-year jumps. Perhaps this is minor and acceptable?

**Comment by gregallensworth** [comment]
This is a contrived (fake data!) example of a near-worst-possible case of "lumpy chronology" in which we are missing data for several years in a row but also have data for several years in a row. The gaps from 1972-1980 and 1982-1992 have no visual indication, and appears as visually contiguous as  consecutive years such as 1980-1982.

![image](https://user-images.githubusercontent.com/3117633/36223779-4950f456-117a-11e8-9999-8ef230f6b912.png)

Problem is, we can't have everything: accurately showing actual-data years, while also padding out the years t create even spacing, while also not generating intentional nodata rows. *The real fix is to get the missing election data.*

**Comment by gregallensworth** [comment]
### Front Page Map

This has been updated, to coerce odd-numbered years to be even by adding 1. Thus the plan dated 1973, will be rewritten to match 1974 on the map. This seems not misleading, as the 1973 plan was almost certainly the one in effect in 1974, while the next plan 2 years later in 1975 would be the one in effect in 1976.

![image](https://user-images.githubusercontent.com/3117633/36224825-918cae7e-117d-11e8-9b21-2f27eb1dfde9.png)

**Comment by gregallensworth** [comment]
Per the above item about spacing and gaps: https://github.com/PlanScore/PlanScore/issues/217#issuecomment-365719654

Revisit the idea of adding do-nothing rows to generate visual space: no click handler (so no nodata condition), no year display, just the `plan-continue` line and emptiness.

At its most basic we would need to add such a gap for every single year, so a schedule with both evens and odds could fit in a linear fashion. *But, this would make the yearpicker 45 rows in height, double its previous height and taller than even generous desktop displays.*

I was thinking instead, of finding gaps in excess of 2 years and filling them in with every-2-years from the lower end of the gap. This would not be perfect as a gap of 3 or 5 years would get the same visual spacing as a gap of 4 or 6 years, but that should be acceptable since the idea is to communicate a gap, and not show great detail.

**Comment by gregallensworth** [comment]
Gaps in the election data, are now represented with blank rows. This preserves the spacing in chronology, while not specifically inviting clicks and the expectation of data.

These blank rows are still "active" in that they highlight when the plan is selected, and can be clicked to find the previous year-and-plan and trigger it for display.  **As a result, when we reinstate Election displays, this "find the closest" may become undesirable.**

<img width="750" alt="fakedata gaps get spacing" src="https://user-images.githubusercontent.com/3117633/36228935-77b4696c-118a-11e8-90a3-f35ba21d8eea.png">




Some state-and-districttype combinations have 4-year cycles and not 2-year cycles (MS statehouse, AL statehouse). These are programmed in as exceptions, and their "gap padding" is adjusted accordingly. In the example below, the 4-year gaps are *not* padded with empty rows, as they are not empty nor missing data, but just outside of MS-statehouse's cycle.

<img width="736" alt="al statehouse every 4 years" src="https://user-images.githubusercontent.com/3117633/36228934-7795dfec-118a-11e8-8b5c-b0b3a7060d76.png">

**Comment by gregallensworth** [comment]
A new PR is in place for this, based on the `gda-217-oddyears` branch. If the screenshots above are to your liking, go ahead and merge it. Or, check out `gda-217-oddyears` for some local testing.
