### ISSUE TITLE
homepage odd-year fudge creates unexpected missing data UX on state page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#223]
From #217:

@migurski noted:
>Actually, one weird thing. When I click on VA from the front page to a URL like /virginia/#!2002-plan-statehouse, I get a “No plan data are available” error.

And @gregallensworth responded:

>That is correct: there are no data for VA statehouse 2002 There are data for VA statehouse 2000 and 2004, and for VA ushouse 2002, but not statehouse 2002. The state links and also the map, are sensitive to the selected district type and year, sending you to in theory the same data that you're seeing in front of you. The behavior you're seeing is expected. If you would like this behavior of the front-page to change, let's open a new issue in that regard. 

I hadn't thought of this particular consequence of fudging home page view of odd-year elections. This is expected only if one knows we're fudging odd years. To an unsuspecting user, VA is colored in on home page in 2002 on home page but then I click on it to see more and get No Data. Reads as an error.

Not sure yet what the fix is. But I do think this will read as a bug to users

**Comment by gregallensworth** [comment]
Ahhhh, now I see what you were getting at. On the state page, it's true that VA has no data for 2002... but seems weird that someone would land there instead of on 2001. On the front page, the misrepresentation of 2001 data as being 2002, is convenient for drawing on the map but not so great when we "turn to 2002" to see data.

There *is* the "we don't have data try YYYY instead" behavior but landing at the right year would be great.

Thinking...

**Comment by gregallensworth** [comment]
Rubber ducking this off GIthub and my own fingers...

#### Alter the front page, to somehow store plan data instead of current-year

This means a complete reworking of the concepts used in the map and the listings, as the `CURRENT_VIEW.year` is the timeline selection, and is relatively unintelligent about Plan years. It uses a straight filter `row.year == CURRENT_VIEW.year` which misses odds (and at any rate, doesn't know that the plan started in 2001).

Instead, would need to:
* on CSV load, form a structure of years and plans (and notably plan startyears) from the CSV content
* rewrite state listing & popup links, to detect *plan in effect during CURRENT_VIEW.year* and thus startyear, and instead link to the state page with that year

Pro & Con:
* Does solve issue
* Rather situational, fixing only this one situation of this page generating links
* Significant rewrite of whole front page; all day


#### Improve state pages behavior when nodata year selected

Have the state page detect a no-data condition on page load, and have it pick a year for which we do have data. *Then* have it actually forward to that hash and load the data, instead of just displaying the "we have no data, did you mean YYYY"

* Simpler fix, expanding on behaviors described in #219 
* In fact, most of the logic for this is already in place, and should adapt readily
* Makes state pages more fault tolerant of folks linking to nodata years, rather than a situational fix specific to the front page (link to 1984 or 1988, whatever; it'll fix it for you)

**Comment by gregallensworth** [comment]
Example URL:     http://local.planscore.info:8000/virginia/#!2002-plan-statehouse-eg

There are no data for *VA statehouse 2002* as this is a 2001-2003 plan. This is exactly our intended case, in which the front-page map (or erroneous links, generated lists of links, just trying links, etc) would send us to a year, but we would prefer to be silently forwarded to a working year.

This new behavior has been programmed in:
* *On page load* if you specify a district+year for which there are no data, it finds the `plan_minyear` of the Plan that was active at this time, then silently picks that year for you.
  * Thus, the link to 2002 VA statehouse silently selects 2001 for you, showing data, updating the URL, etc.
  * Thus the state page is now more fault-tolerant should one supply a link resulting in a no data condition.
* *In other cases* such as switching boundary types, behavior remains the same. It displays a link advising that X is the closest year, and one may choose to click it or switch districts etc.
  * This makes for smoother UX when one is switching boundary types, and may want to continue browsing the data.
  * This also retains compatibility for eventual reinstatement of Election mode.

**Comment by gregallensworth** [comment]
Commit 9a21187 adds a workaround for years-in-URLs which are completely out of range, e.g. 

http://local.planscore.info:8000/virginia/#!1900-plan-ushouse-eg
http://local.planscore.info:8000/virginia/#!2016-plan-statehouse-eg

Since no Plan was found "bracketing" the target year, a second check is done whether the target year is >max or <min of all years encountered. It would then pick the earliest or latest year possibly available.

This works for both totally extreme outliers (the 1900 example above, or 2100) as well as some real-world edge cases such as *VA statehouse 2016* where the data end at 2011

**Comment by migurski** [comment]
I’m still seeing some buggy behavior related to this. In particular, switching between Virginia state house and U.S. house views always shows the "no plan data" issue.

**Comment by danrademacher** [comment]
I want to be sure I understand what's happening here -- there's one way of reading this that would involve unpacking some of our assumptions about coming from home page vs switching tabs within state page. Which is fine.

BUT I am still seeing a difference in behavior on the live site vs local test, same as we were seeing this morning and thought we identified as a caching issue.

## Local, expected behavior, clicking VA from 2014 State on home > 2013 VA State
![local_correct_2joqoud81l](https://user-images.githubusercontent.com/1423200/36518847-0efd948a-173d-11e8-9ea0-fdfb91e1d046.gif)

## Live site, incorrect behavior, clicking VA from 2014 State on home > No data message, try 2013:
![live_broken_qmwnju8ujl](https://user-images.githubusercontent.com/1423200/36518869-2969c4d8-173d-11e8-9eec-ffa61e02d514.gif)

Maybe we need to do another _something_ to get live site to match local?

And then circle back and see if we're still needing to address inconsistent behavior between home>state event, vs within state (which we did make slightly different with the thought that user intent on state page is harder to divine as they move around years and house levels).

**Comment by migurski** [comment]
Sorry, I wasn't clear enough in my comment! I’m looking at `/virginia/#!1998-plan-ushouse-eg` at commit 0d5d717 ([here’s a live link](https://precog-website.herokuapp.com/PlanScore/PlanScore/0d5d717/virginia/#!1998-plan-ushouse-eg)) and switching between U.S. House and State House.

When I click State House, I get “No plan data … try 1999”. That links me to `/virginia/#!1999-plan-statehouse-eg`. Then I click U.S. House and get “No plan data … try 2000.” That links me to `/virginia/#!2000-plan-ushouse-eg`. At no point does switching chambers in Virginia show data, though it does work when following those links from the front page.

(I’m punting on the live site caching behavior for now, and checking these behaviors without the CDN)

**Comment by gregallensworth** [comment]
### Dan's Report: Front page linking to State

I am not seeing the behavior Dan describes.

Live site *planscore.org* OSX-Safari and Windows-Chrome

* Front page, select 2014 State House
* Click VA and get popup
* Follow link, arrive at `/virginia/#!2014-plan-statehouse-eg`
* In blink of an eye this loads 2013 and updates to /virginia/#!2013-plan-statehouse-eg  The no data message is not visible, but the 2011-2013 redistricting plan is displayed.

If you are still seeing this issue, can you clear your cache and walk me through it one click at a time? Maybe I'm not reading your description quite right?


### Michal's Report

I am not seeing the behavior you describe of being in a loop between 1999 and 2000:

* Start at https://planscore.org/virginia/#!1998-plan-ushouse-eg and see 1998-2000 US House plan
* Click State House, see expected: no data and suggestion to use 1999 (but do not click 1999)
* Click directly back to US House, see 1998-2000 US House plan again
* Click State House, see expected: no data and suggestion to use 1999 (and this time click 1999)
* Page adjusts to https://planscore.org/virginia/#!1999-plan-statehouse-eg and shows me the 1991-1999  State House plan
* Click US House, see expected "no data, try 2000" (click it)
* Arrive at 1999-2000 US House plan https://planscore.org/virginia/#!2000-plan-ushouse-eg

If you are still seeing this issue, can you clear your cache and walk me through it one click at a time? Maybe I'm not reading your description quite right?

The different behavior you are seeing btween *switching boundaries* and when *landing on the page*, is as intended. This was described in https://github.com/PlanScore/PlanScore/issues/223#issuecomment-366021566 and also in PR #224: *Again, note that this "snap to active plan" behavior is specifically on page load and switching between district types keeps the prior "suggest a year" behavior.*

The intent of issue 223 was to address people linking to the page using arbitrary years, but in other discussions we elected to avoid further "magical" behavior once they were on the page and intentionally switching between things. This behavior also retains compatibility with Election Year display, which is still supported though no UI is presented.

**Comment by danrademacher** [comment]
I have split this out into a new #241

**Comment by gregallensworth** [comment]
Issue 241 regards a change in the `fudgeYearIfNoData` behavior, that it *will* happen on subsequent UI changes, and not only on page load *when in Plan mode*. This was one of the components of Michal's report.
