### ISSUE TITLE
Make state click on home page go directly to state page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#238]
Related to #236, let's try making a click on state on the map go directly to state page, wiring around the popover.

It might make sense to leave popover in place but just change the behavior so it is not invoked. Then we let it run that way for a week or three, look at GA again. 

* If we're seeing more/better state page conversion, then we excise popover entirely. 
* If conversion is same or worse _and_ time-on-page degrades for Home, then we bring back popover and try another solution to encouraging users to go from home to state pages.

**Comment by gregallensworth** [comment]
Dan asks for two new behaviors on the states:
* command-click opens in new window
* right-click opens contextual menu

The context menu is not possible, as these aren't hyperlinks at all but click events on a SVG canvas. While one could write code to intercept a `contextmenu` event (right-click), the behavior wouldn't be at all straightforward to define. A DIV could be created with content, but wouldn't realistically mimic the behavior of any specific browser, let alone each browser's behavior (inspect element, incognito, copy address, bookmark target page, ...).

Intercepting the command/alt/shift/ctrl keys on the click, though, is readily feasible. Opening using `window.open()` instead of `document.location.href` should be readily feasible as well.

**Comment by gregallensworth** [comment]
Latest commit adds ctrl/shift/alt//command detection. Note that browsers have some variation as to what `window.open` means and there's nothing we can do about that; W3C specs don't offer a mechanism to suggest that one would prefer a window or tab.

On Chrome for Windows the behaviors are as follows:
* shift -- new window
* alt -- new tab, and switch to it
* ctrl -- new tab, do not switch to it
