### ISSUE TITLE
Look at rolling dynamic sentences into production data CSVs

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#66]
Per #64, we have some cleaner spreadsheets here:
`us_house_production`: https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=1340994475
and
`state_house_production`:
https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=1167907324

Let's look at using simple formulas in there to generate sentences like this:

>+20% EG: Democrats had to earn 20% more votes to achieve 4/13 seats than they would under a fair plan.

**Comment by danrademacher** [comment]
Tested here: https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=1340994475&range=P:R

Flipped the valence however of the wording, since I'm pretty sure +20 *R* sentence should focus on R needing fewer votes vs D needing more votes.

**Comment by gregallensworth** [comment]
The sentences can be constructed dynamically within the program, based on the eg_adj, seats, seats_dem, seats_r fields. This may make for better flexibility as they want to change the wording several more times, without needing to redo the spreadsheets, as well as moderately smaller/faster CSV downloads.

Would there be a need for the wording to be truly custom, instead of generated from those fields?

**Comment by danrademacher** [comment]
Yes, I'm on the fence about whether this should be in JS or in the source data as static text. Short of "truly custom", I would expect iteratively complex logic, like:
```
If eg_adj < threshold, then 
"this plan is neutral"
else
...
```

Hmm, sounds like a better fit for a `case` or `switch` statement in the code vs in spreadsheet.

**Comment by danrademacher** [comment]
Settled that we're doing this in code.

Specifically here:
https://github.com/PlanScore/PlanScore/blob/gh-pages/_statetemplate/state_template.js6#L222
